GET http://localhost:8080/user HTTP/1.1
Authorization: $2b$07$7oAwFQrfKboUT6xdVCH9Au8PcQifhYtyzoWC.eZRzeuAlt6HYAK3G


### 
POST http://localhost:8080/user/register HTTP/1.1
Content-Type: application/json

{
    "name":"Xasanboy",
    "lastname":"Abdurasulov",
    "email":"Xasanboy@gmail.com",
    "password":1234
}

###
POST http://localhost:8080/user/login HTTP/1.1
Content-Type: application/json

{
    "name":"Xasanboy",
    "lastname":"Abdurasulov",
    "email":"Xasanboy@gmail.com",
    "password":1234567891
}

###
GET http://localhost:8080/user/5 HTTP/1.1
Authorization: Hello World

###
DELETE http://localhost:8080/user/1 HTTP/1.1
Content-Type: application/json
Authorization: Hello

{
    "id":10,
    "name":"Xasanboy",
    "lastname":"Abdurasulov",
    "email":"hasanbojabdurasulov309@gmail.com",
    "password":"eyJhbGciOiJIUzI1NiJ9.JDJiJDA3JE5TVElIZWQ4RmZMUHBDemt3YXFkRnVHRHRuLk00R0xnUVNjSS52bGpmMFNMaWFqNHVjSGp1.hF38wEEkHe8wjmZeAdtW0BDnq_R2WqTMf14yc6nwcKU"
}

###
POST http://localhost:8080/admin/5 HTTP/1.1
Content-Type: application/json


###
# Get All Products
GET http://localhost:8080/product HTTP/1.1
Authorization: Hello World

###
POST http://localhost:8080/product/1
Content-Type: application/json
Authorization: Hello World

{
    "name":"Phone",
    "price":120,
    "description":"Very Fast",
    "author":5,
    "number":"Electronics"
}

###
DELETE http://localhost:8080/product/5
Content-Type: application/json

{
    "remove":20
}

###
PATCH  http://localhost:8080/product/5
Content-Type: application/json

{
    "product":21,
    "name":"Phone",
    "price":120,
    "description":"Very Fast",
    "author":5,
    "number":"Electronics"
}

#                    Basket
###
GET http://localhost:8080/basket/1   HTTP/1.1
Content-Type: application/json
Authorization: Hello World

###
POST http://localhost:8080/basket/1 HTTP/1.1
Content-Type: application/json
Authorization: Hello

{
    "id":9
}
