GET http://localhost:8080/user HTTP/1.1
Authorization:$2b$07$rRDj6ZfyFW5lVi0hpgysC.bJzEWQTeNlIl.zHWaxqXRVWgt/61Kdy


### 
POST http://localhost:8080/user/register HTTP/1.1
Content-Type: application/json
Authorization:$2b$07$E7Z4A8XCBchVRDs5c2NYTOPp5m4x19J35gjCi4emNOCZheoCuMhw6


{
    "name":"Xasanboy",
    "lastname":"Abdurasulov",
    "email":"Xasan@gmail.com",
    "password":1234
}

###
POST http://localhost:8080/user/login HTTP/1.1
Content-Type: application/json

{
    "email":"Xasan@gmail.com",
    "password":1234
}

###
GET http://localhost:8080/user/5 HTTP/1.1
Authorization: Hello World

###
DELETE http://localhost:8080/user/1 HTTP/1.1
Content-Type: application/json
Authorization: Hello

{
    "id":10,
    "name":"Xasanboy",
    "lastname":"Abdurasulov",
    "email":"hasanbojabdurasulov309@gmail.com",
    "password":"eyJhbGciOiJIUzI1NiJ9.JDJiJDA3JE5TVElIZWQ4RmZMUHBDemt3YXFkRnVHRHRuLk00R0xnUVNjSS52bGpmMFNMaWFqNHVjSGp1.hF38wEEkHe8wjmZeAdtW0BDnq_R2WqTMf14yc6nwcKU"
}

###
POST http://localhost:8080/admin/1 HTTP/1.1
Content-Type: application/json